In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3,4,5,6,7,8,9,10])

In [4]:
v / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [5]:
v * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
v ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [7]:
# yukarıdaki işlemleri operatörler aracılığıyla kolayca gerçekleştirebildik, onun haricinde eğer metotları kullanmak istersek onları da kolayca kullanabiliriz. 




In [8]:
np.subtract(v,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.add(v,2)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
np.mean(v)

5.5

In [11]:
np.min(v)

1

In [12]:
np.max(v)

10

In [13]:
np.var(v)

8.25

In [15]:
# Numpy ile iki bililnmeyenli bir denklem çöözümü

# 5*x0 + x1 = 12
# x0 + 3*x1 = 10

a = np.array([[5,1], [1,3]])
b = np.array([12,10])

np.linalg.solve(a,b)

array([1.85714286, 2.71428571])